
###
GET http://localhost:3000/api/blocks
Content-Type: application/json



###
POST http://localhost:3000/api/mine
Content-Type: application/json


{
    "data" : "foo-data"
}

###
POST http://localhost:3000/api/transactions
Content-Type: application/json


{
    "recipient" : "foo",
    "amount" : 75
}

###
GET http://localhost:3000/api/transactions-miner